project:
  type: website
  render: 
    - "*.qmd"
    - "*/*.qmd"

website:
  title: "Farmhill Curriculum"
  
  page-navigation: true
  navbar:
    logo: farmhill-logo2.png 
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - maths/index.qmd
      - science/index.qmd
  sidebar:
    - id: default
      style: docked
      contents: []

    - id: maths
      contents:   
        - maths/Early-years.qmd
        - maths/primary.qmd
        - maths/Secondary.qmd
        - maths/Senior-secondary.qmd
    - id: science
      contents: []
  
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full



