project:
  type: website
  render: 
    - "*.qmd"
    - "*/*.qmd"

website:
  title: "Farmhill Curriculum"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - maths/index.qmd
      - science/index.qmd
  sidebar:
    - id: default
      style: docked
      contents: auto

  # - id: maths
   #     contents: auto
   #- id: science
    #contents: auto
  
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full



